### ISSUE TITLE
Back to previous menu

### ISSUE THREAD

**Issue by jaclu** [alexwforsythe/tmux-which-key#8]
Hi, I really apreciate somebody else also working with tmux menus!
My perhaps slightly over engineered aproach is at jaclu/tmux-menus

Using yaml for menu design certainly makes for easy config!

However one thing I almost immeditally noticed, was that as I opened various menus to see what was in there, there was no going back, so adding a back or previous menu option would be a huge usability gain.

Anyhow pretty neat!

**Comment by JeffChien** [comment]
```yaml
      - name: Back
        key: BSpace
        command: 'show-wk-menu #{@wk_menu_windows}'
```
this is my workaround by adding the backspace to upper layer.
